### ISSUE TITLE
Only generate files that don't exist 

### ISSUE THREAD

**Issue by una** [Sass-Director/Sass-Director_Sublime#2]
This will prevent overwriting files when you run sass director more than just the first time. Currently, running it will clear any code written within existing files

**Comment by lunelson** [comment]
I just ran in to this. Too dangerous, uninstalled 😬

**Comment by una** [comment]
:( ugh so sorry

**Comment by lunelson** [comment]
It's too bad — it's a really nice workflow tool, but for now I'll use the online version. 

I'm curious: is there no easy equivalent here to the `touch` terminal command (which obviously does not overwrite existing files)?

**Comment by lunelson** [comment]
I don't know python but it seems like the flag passed to the `open` command on [this line](https://github.com/Sass-Director/Sass-Director_Sublime/blob/master/sass-director.py#L134) could be changed (probably to `x`) and this issue would be resolved

Reference re: flags https://docs.python.org/3/library/functions.html#open

**Comment by lunelson** [comment]
Some more alternatives in [this thread](https://bytes.com/topic/python/answers/159301-best-way-touch-file) too; but I think the flag change might do it, I just don't know how to handle the error in python

**Comment by una** [comment]
I'll look into it!

**Comment by lunelson** [comment]
(please close)
